# Generated by Django 5.0.6 on 2024-08-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_room_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='picture',
            field=models.ImageField(blank=True, default='room_pictures/default.png', null=True, upload_to='room_pictures/'),
        ),
    ]
