services:
  backend:
    container_name: backend
    image: backend
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 8000:8000
    networks:
      - transcendence
    depends_on:
      - postgres


  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    expose:
      - $POSTGRES_PORT
    networks:
      - transcendence
    volumes:
      - database:/var/lib/postgresql/data

networks:
  transcendence:
    driver: bridge

volumes:
  database:
