services:
  front:
    container_name: front
    image: front
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - transcendence
    volumes:
      - ./front:/app
    develop:
      watch:
        - action: sync
          target: /app
          path: ./front

  back:
    container_name: back
    image: back
    build:
      context: ./back
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./back
          action: sync+restart
          target: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - transcendence
      #    volumes:
      #- ./back:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - transcendence
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - HOST_HOSTNAME=$HOST_HOSTNAME
    ports:
      - "3000:80"
      - "5000:443"
    networks:
      - transcendence
    volumes:
      - ./front:/usr/share/nginx/app
      - ./back/media:/usr/share/nginx/media
      - ssl_certs:/etc/ssl
    depends_on:
      - back
      - front

networks:
  transcendence:
    driver: bridge

volumes:
  database:
  ssl_certs:
