services:
  server:
    container_name: server
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 8000:8000
    networks:
      - transcendence
    volumes:
      - static:/app/static
    depends_on:
      - postgres


  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    expose:
      - $POSTGRES_PORT
    networks:
      - transcendence
    volumes:
      - database:/var/lib/postgresql/data


  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    networks:
      - transcendence
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - static:/app/static
    depends_on:
      - server



networks:
  transcendence:
    driver: bridge

volumes:
  static:
  database:
