services:
  web:
    container_name: web
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - HOST_HOSTNAME=$HOST_HOSTNAME
    ports:
      - 8000:8000
    networks:
      - transcendence
    volumes:
      - $DJANGO_VOLUME:/app

  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - transcendence
    volumes:
      - database:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - HOST_HOSTNAME=$HOST_HOSTNAME
    ports:
      - 3000:3000
    networks:
      - transcendence
    volumes:
      - $NGINX_STATIC_VOLUME:/usr/share/nginx/static
      - $NGINX_MEDIA_VOLUME:/usr/share/nginx/media
      - ssl_certs:/etc/ssl

networks:
  transcendence:
    driver: bridge

volumes:
  database:
  ssl_certs:
