services:
  web:
    container_name: web
    image: web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 8000:8000
    networks:
      - transcendence
    volumes:
      - $DJANGO_VOLUME:/app
    depends_on:
      db:
        condition: service_healthy


  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - transcendence
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - transcendence
    volumes:
      - $NGINX_VOLUME:/usr/share/nginx/static
    depends_on:
      - web


networks:
  transcendence:
    driver: bridge

volumes:
  database: