services:
  back:
    container_name: back
    image: back
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      HOST_HOSTNAME: $HOST_HOSTNAME
    ports:
      - 8000:8000
    networks:
      - transcendence
    volumes:
      - static:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy


  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"
    networks:
      - transcendence
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - HOST_HOSTNAME=$HOST_HOSTNAME
    ports:
      - 3000:3000
    networks:
      - transcendence
    volumes:
      - $NGINX_VOLUME_LOCATION:/app/static
    depends_on:
      - back


networks:
  transcendence:
    driver: bridge

volumes:
  static:
  database:
