# Generated by Django 5.0.6 on 2024-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='connected_players',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('started', 'Started'), ('finished', 'Finished')], default='waiting'),
        ),
    ]
