# Generated by Django 5.0.6 on 2024-10-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='connected_players',
        ),
    ]
