# Generated by Django 5.0.6 on 2024-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_game_connected_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('finished', 'Finished')]),
        ),
    ]
