# Generated by Django 5.0.6 on 2024-10-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('started', 'Started'), ('finished', 'Finished')], default='waiting'),
        ),
    ]
