# Generated by Django 5.0.6 on 2024-07-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='media/profile-pictures/'),
        ),
    ]
