# Generated by Django 5.0.6 on 2024-10-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_invitation_status'),
        ('game', '0003_remove_game_connected_players_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game'),
        ),
    ]
