# Generated by Django 5.0.6 on 2024-10-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatroom_name'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='duel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gamemodel'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_duel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_duel_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_duel_expired',
            field=models.BooleanField(default=False),
        ),
    ]
