# Generated by Django 5.0.6 on 2024-10-31 11:13

import account.utils.defines
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='twofa_method',
            field=models.IntegerField(default=account.utils.defines.TWO_FA_METHOD['EMAIL']),
        ),
    ]
