# Generated by Django 5.0.6 on 2024-07-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, default='profile-pictures/default.png', null=True, upload_to='profile-pictures/'),
        ),
    ]
