# Generated by Django 5.0.6 on 2024-10-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_level_customuser_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
