# Generated by Django 5.0.6 on 2024-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customuser_otp_secret_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='code',
        ),
        migrations.AddField(
            model_name='otp',
            name='secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
